### PR TITLE
Update for Laravel 5.2 and legacy compactibility

### PR DESCRIPTION
**Pull request by Maxime-BHA**
Changing bindShared as it's deprecated in 5.1 and removed from 5.2.

### CODE REVIEW

**Comment by JoshHarmon** [comment]
We're not going to be using 5.2, but as it's deprecated in 5.1, this might still be worthwhile.

**Comment by euantorano** [comment]
I think it's worthwhile staying as close to the latest release as we can. 5.2 brings some nice new features. So long as it's still compatible with PHP 5.5.9, we can use it.

**Comment by JoshHarmon** [comment]
@euantorano I ninja-deleted my comment after I saw your commit. I thought the whole point of being on 5.1 though was to have as long of a framework short cycle as possible before people potentially have to update their environments for new Laravel versions.

**Comment by euantorano** [comment]
Yeah, I noticed that ;)

IMO, so long as the versions still have the same server requirements, we should be OK to stick with them. The whole 5.x line should be following semantic versions and shouldn't change anything major like PHP requirements.

**Comment by Maxime-BHA** [comment]
@JoshHarmon IMHO, whatever the Laravel version your team is going to stick to, bindShared has been  deprecated on 5.1 and removed from 5.2, however, Laravel has always introduced minor breaking change through differents minor release, see 5.1.0 and 5.1.11

I would rather suggest you, and your team, to stick to the newest release, or just set a 5.1 version as MyBB main Laravel version, it could be really tiresome to update all your dependencies for each new Laravel version, as the framework is constantly evolving.

@euantorano Laravel is not following semantic versionning as @GrahamCampbell specified on https://github.com/laravel/framework/issues/10625, also he said even 5.3 will keep compactibility with PHP 5

**Comment by JoshHarmon** [comment]
@Maxime-BHA I'm mostly in support of staying updated with the Laravel releases. However, I wasn't aware that we made the decision as a team to upgrade to 5.2 (or later, eventually?). If you saw my comment before I retracted it, I mentioned that I agree it's still worth changing because of bindShared being deprecated. Also, thenk you for the link I was looking for.

**Comment by euantorano** [comment]
Alright, we'll merge this and keep my changes for the 5.2 upgrade. I'll open a topic discussing how we should track Laravel releases.

**Pull request merged**
